# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\programming\warmachine_tourney\GUI\mainwindow.ui'
#
# Created: Sun Jul 07 11:56:20 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_players = QtGui.QWidget()
        self.tab_players.setObjectName("tab_players")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_players)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.c_faction = QtGui.QComboBox(self.tab_players)
        self.c_faction.setObjectName("c_faction")
        self.c_faction.addItem("")
        self.c_faction.addItem("")
        self.c_faction.addItem("")
        self.c_faction.addItem("")
        self.c_faction.addItem("")
        self.c_faction.addItem("")
        self.c_faction.addItem("")
        self.c_faction.addItem("")
        self.c_faction.addItem("")
        self.c_faction.addItem("")
        self.c_faction.addItem("")
        self.gridLayout.addWidget(self.c_faction, 1, 1, 1, 1)
        self.e_country = QtGui.QLineEdit(self.tab_players)
        self.e_country.setObjectName("e_country")
        self.gridLayout.addWidget(self.e_country, 1, 3, 1, 1)
        self.e_name = QtGui.QLineEdit(self.tab_players)
        self.e_name.setObjectName("e_name")
        self.gridLayout.addWidget(self.e_name, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_players)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab_players)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label = QtGui.QLabel(self.tab_players)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.e_team = QtGui.QLineEdit(self.tab_players)
        self.e_team.setObjectName("e_team")
        self.gridLayout.addWidget(self.e_team, 1, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab_players)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        self.b_addPlayer = QtGui.QPushButton(self.tab_players)
        self.b_addPlayer.setObjectName("b_addPlayer")
        self.gridLayout.addWidget(self.b_addPlayer, 1, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.t_players = QtGui.QTableWidget(self.tab_players)
        self.t_players.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.t_players.setAlternatingRowColors(True)
        self.t_players.setRowCount(5)
        self.t_players.setColumnCount(10)
        self.t_players.setObjectName("t_players")
        self.t_players.setColumnCount(10)
        self.t_players.setRowCount(5)
        item = QtGui.QTableWidgetItem()
        self.t_players.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.t_players.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.t_players.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.t_players.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.t_players.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.t_players.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.t_players.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.t_players.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.t_players.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.t_players.setHorizontalHeaderItem(9, item)
        self.t_players.horizontalHeader().setDefaultSectionSize(100)
        self.t_players.horizontalHeader().setSortIndicatorShown(False)
        self.t_players.horizontalHeader().setStretchLastSection(True)
        self.t_players.verticalHeader().setVisible(False)
        self.t_players.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout.addWidget(self.t_players)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_19 = QtGui.QLabel(self.tab_players)
        self.label_19.setStyleSheet("font-weight:bold;")
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 0, 0, 1, 1)
        self.e_country_2 = QtGui.QLineEdit(self.tab_players)
        self.e_country_2.setObjectName("e_country_2")
        self.gridLayout_4.addWidget(self.e_country_2, 2, 4, 1, 1)
        self.label_21 = QtGui.QLabel(self.tab_players)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 1, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.tab_players)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 1, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.tab_players)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 1, 4, 1, 1)
        self.label_23 = QtGui.QLabel(self.tab_players)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 1, 3, 1, 1)
        self.label_22 = QtGui.QLabel(self.tab_players)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 1, 2, 1, 1)
        self.c_faction_2 = QtGui.QComboBox(self.tab_players)
        self.c_faction_2.setObjectName("c_faction_2")
        self.c_faction_2.addItem("")
        self.c_faction_2.addItem("")
        self.c_faction_2.addItem("")
        self.c_faction_2.addItem("")
        self.c_faction_2.addItem("")
        self.c_faction_2.addItem("")
        self.c_faction_2.addItem("")
        self.c_faction_2.addItem("")
        self.c_faction_2.addItem("")
        self.c_faction_2.addItem("")
        self.c_faction_2.addItem("")
        self.gridLayout_4.addWidget(self.c_faction_2, 2, 2, 1, 1)
        self.e_name_2 = QtGui.QLineEdit(self.tab_players)
        self.e_name_2.setObjectName("e_name_2")
        self.gridLayout_4.addWidget(self.e_name_2, 2, 1, 1, 1)
        self.e_team_2 = QtGui.QLineEdit(self.tab_players)
        self.e_team_2.setObjectName("e_team_2")
        self.gridLayout_4.addWidget(self.e_team_2, 2, 3, 1, 1)
        self.e_pUid = QtGui.QLineEdit(self.tab_players)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.e_pUid.sizePolicy().hasHeightForWidth())
        self.e_pUid.setSizePolicy(sizePolicy)
        self.e_pUid.setObjectName("e_pUid")
        self.gridLayout_4.addWidget(self.e_pUid, 2, 0, 1, 1)
        self.b_editPlayer = QtGui.QPushButton(self.tab_players)
        self.b_editPlayer.setObjectName("b_editPlayer")
        self.gridLayout_4.addWidget(self.b_editPlayer, 2, 5, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.tabWidget.addTab(self.tab_players, "")
        self.tab_pairings = QtGui.QWidget()
        self.tab_pairings.setObjectName("tab_pairings")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_pairings)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtGui.QLabel(self.tab_pairings)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.c_pairRound = QtGui.QComboBox(self.tab_pairings)
        self.c_pairRound.setEnabled(False)
        self.c_pairRound.setObjectName("c_pairRound")
        self.horizontalLayout_2.addWidget(self.c_pairRound)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.b_startNextRound = QtGui.QPushButton(self.tab_pairings)
        self.b_startNextRound.setObjectName("b_startNextRound")
        self.horizontalLayout_2.addWidget(self.b_startNextRound)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.t_pairings = QtGui.QTableWidget(self.tab_pairings)
        self.t_pairings.setAutoFillBackground(False)
        self.t_pairings.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.t_pairings.setAlternatingRowColors(True)
        self.t_pairings.setRowCount(5)
        self.t_pairings.setObjectName("t_pairings")
        self.t_pairings.setColumnCount(4)
        self.t_pairings.setRowCount(5)
        item = QtGui.QTableWidgetItem()
        self.t_pairings.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.t_pairings.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.t_pairings.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.t_pairings.setHorizontalHeaderItem(3, item)
        self.t_pairings.horizontalHeader().setStretchLastSection(True)
        self.t_pairings.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.t_pairings)
        self.tabWidget.addTab(self.tab_pairings, "")
        self.tab_results = QtGui.QWidget()
        self.tab_results.setObjectName("tab_results")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.tab_results)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtGui.QLabel(self.tab_results)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.e_tblnum = QtGui.QLineEdit(self.tab_results)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.e_tblnum.sizePolicy().hasHeightForWidth())
        self.e_tblnum.setSizePolicy(sizePolicy)
        self.e_tblnum.setObjectName("e_tblnum")
        self.horizontalLayout_4.addWidget(self.e_tblnum)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.e_pAcp = QtGui.QLineEdit(self.tab_results)
        self.e_pAcp.setObjectName("e_pAcp")
        self.gridLayout_2.addWidget(self.e_pAcp, 2, 4, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab_results)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab_results)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 4, 1, 1)
        self.e_pAuid = QtGui.QLineEdit(self.tab_results)
        self.e_pAuid.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.e_pAuid.sizePolicy().hasHeightForWidth())
        self.e_pAuid.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.e_pAuid.setFont(font)
        self.e_pAuid.setObjectName("e_pAuid")
        self.gridLayout_2.addWidget(self.e_pAuid, 2, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.tab_results)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 5, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab_results)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.e_pAname = QtGui.QLineEdit(self.tab_results)
        self.e_pAname.setEnabled(False)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.e_pAname.setFont(font)
        self.e_pAname.setObjectName("e_pAname")
        self.gridLayout_2.addWidget(self.e_pAname, 2, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab_results)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 3, 1, 1)
        self.e_pAkp = QtGui.QLineEdit(self.tab_results)
        self.e_pAkp.setObjectName("e_pAkp")
        self.gridLayout_2.addWidget(self.e_pAkp, 2, 5, 1, 1)
        self.e_pAtp = QtGui.QLineEdit(self.tab_results)
        self.e_pAtp.setText("")
        self.e_pAtp.setObjectName("e_pAtp")
        self.gridLayout_2.addWidget(self.e_pAtp, 2, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab_results)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.tab_results)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 1, 2, 1, 1)
        self.c_pAfaction = QtGui.QComboBox(self.tab_results)
        self.c_pAfaction.setEnabled(True)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.c_pAfaction.setFont(font)
        self.c_pAfaction.setObjectName("c_pAfaction")
        self.c_pAfaction.addItem("")
        self.c_pAfaction.addItem("")
        self.c_pAfaction.addItem("")
        self.c_pAfaction.addItem("")
        self.c_pAfaction.addItem("")
        self.c_pAfaction.addItem("")
        self.c_pAfaction.addItem("")
        self.c_pAfaction.addItem("")
        self.c_pAfaction.addItem("")
        self.c_pAfaction.addItem("")
        self.c_pAfaction.addItem("")
        self.gridLayout_2.addWidget(self.c_pAfaction, 2, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.e_pBname = QtGui.QLineEdit(self.tab_results)
        self.e_pBname.setEnabled(False)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.e_pBname.setFont(font)
        self.e_pBname.setObjectName("e_pBname")
        self.gridLayout_3.addWidget(self.e_pBname, 2, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab_results)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 1, 3, 1, 1)
        self.e_pBcp = QtGui.QLineEdit(self.tab_results)
        self.e_pBcp.setObjectName("e_pBcp")
        self.gridLayout_3.addWidget(self.e_pBcp, 2, 4, 1, 1)
        self.label_15 = QtGui.QLabel(self.tab_results)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 1, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.tab_results)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 1, 4, 1, 1)
        self.e_pBtp = QtGui.QLineEdit(self.tab_results)
        self.e_pBtp.setObjectName("e_pBtp")
        self.gridLayout_3.addWidget(self.e_pBtp, 2, 3, 1, 1)
        self.label_13 = QtGui.QLabel(self.tab_results)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 1, 0, 1, 1)
        self.e_pBuid = QtGui.QLineEdit(self.tab_results)
        self.e_pBuid.setEnabled(False)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.e_pBuid.setFont(font)
        self.e_pBuid.setObjectName("e_pBuid")
        self.gridLayout_3.addWidget(self.e_pBuid, 2, 0, 1, 1)
        self.e_pBkp = QtGui.QLineEdit(self.tab_results)
        self.e_pBkp.setObjectName("e_pBkp")
        self.gridLayout_3.addWidget(self.e_pBkp, 2, 5, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab_results)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.tab_results)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 1, 5, 1, 1)
        self.c_pBfaction = QtGui.QComboBox(self.tab_results)
        self.c_pBfaction.setEnabled(True)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.c_pBfaction.setFont(font)
        self.c_pBfaction.setObjectName("c_pBfaction")
        self.c_pBfaction.addItem("")
        self.c_pBfaction.addItem("")
        self.c_pBfaction.addItem("")
        self.c_pBfaction.addItem("")
        self.c_pBfaction.addItem("")
        self.c_pBfaction.addItem("")
        self.c_pBfaction.addItem("")
        self.c_pBfaction.addItem("")
        self.c_pBfaction.addItem("")
        self.c_pBfaction.addItem("")
        self.c_pBfaction.addItem("")
        self.gridLayout_3.addWidget(self.c_pBfaction, 2, 2, 1, 1)
        self.label_28 = QtGui.QLabel(self.tab_results)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 1, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.b_saveResult = QtGui.QPushButton(self.tab_results)
        self.b_saveResult.setObjectName("b_saveResult")
        self.horizontalLayout_5.addWidget(self.b_saveResult)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tab_results, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_players_from_CSV = QtGui.QAction(MainWindow)
        self.actionLoad_players_from_CSV.setObjectName("actionLoad_players_from_CSV")
        self.actionSave_tournament_state = QtGui.QAction(MainWindow)
        self.actionSave_tournament_state.setObjectName("actionSave_tournament_state")
        self.actionLoad_tournament_state = QtGui.QAction(MainWindow)
        self.actionLoad_tournament_state.setObjectName("actionLoad_tournament_state")
        self.actionLoad_Players = QtGui.QAction(MainWindow)
        self.actionLoad_Players.setObjectName("actionLoad_Players")
        self.menuFile.addAction(self.actionSave_tournament_state)
        self.menuFile.addAction(self.actionLoad_tournament_state)
        self.menuFile.addAction(self.actionLoad_Players)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.e_name, self.c_faction)
        MainWindow.setTabOrder(self.c_faction, self.e_team)
        MainWindow.setTabOrder(self.e_team, self.e_country)
        MainWindow.setTabOrder(self.e_country, self.b_addPlayer)
        MainWindow.setTabOrder(self.b_addPlayer, self.e_pUid)
        MainWindow.setTabOrder(self.e_pUid, self.e_name_2)
        MainWindow.setTabOrder(self.e_name_2, self.c_faction_2)
        MainWindow.setTabOrder(self.c_faction_2, self.e_team_2)
        MainWindow.setTabOrder(self.e_team_2, self.e_country_2)
        MainWindow.setTabOrder(self.e_country_2, self.b_editPlayer)
        MainWindow.setTabOrder(self.b_editPlayer, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.t_players)
        MainWindow.setTabOrder(self.t_players, self.c_pairRound)
        MainWindow.setTabOrder(self.c_pairRound, self.b_startNextRound)
        MainWindow.setTabOrder(self.b_startNextRound, self.t_pairings)
        MainWindow.setTabOrder(self.t_pairings, self.e_tblnum)
        MainWindow.setTabOrder(self.e_tblnum, self.e_pAuid)
        MainWindow.setTabOrder(self.e_pAuid, self.e_pAname)
        MainWindow.setTabOrder(self.e_pAname, self.c_pAfaction)
        MainWindow.setTabOrder(self.c_pAfaction, self.e_pAtp)
        MainWindow.setTabOrder(self.e_pAtp, self.e_pAcp)
        MainWindow.setTabOrder(self.e_pAcp, self.e_pAkp)
        MainWindow.setTabOrder(self.e_pAkp, self.e_pBuid)
        MainWindow.setTabOrder(self.e_pBuid, self.e_pBname)
        MainWindow.setTabOrder(self.e_pBname, self.c_pBfaction)
        MainWindow.setTabOrder(self.c_pBfaction, self.e_pBtp)
        MainWindow.setTabOrder(self.e_pBtp, self.e_pBcp)
        MainWindow.setTabOrder(self.e_pBcp, self.e_pBkp)
        MainWindow.setTabOrder(self.e_pBkp, self.b_saveResult)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "WM Masters 2013", None, QtGui.QApplication.UnicodeUTF8))
        self.c_faction.setItemText(0, QtGui.QApplication.translate("MainWindow", "Cygnar", None, QtGui.QApplication.UnicodeUTF8))
        self.c_faction.setItemText(1, QtGui.QApplication.translate("MainWindow", "Cryx", None, QtGui.QApplication.UnicodeUTF8))
        self.c_faction.setItemText(2, QtGui.QApplication.translate("MainWindow", "Khador", None, QtGui.QApplication.UnicodeUTF8))
        self.c_faction.setItemText(3, QtGui.QApplication.translate("MainWindow", "Menoth", None, QtGui.QApplication.UnicodeUTF8))
        self.c_faction.setItemText(4, QtGui.QApplication.translate("MainWindow", "Retribution", None, QtGui.QApplication.UnicodeUTF8))
        self.c_faction.setItemText(5, QtGui.QApplication.translate("MainWindow", "Mercs", None, QtGui.QApplication.UnicodeUTF8))
        self.c_faction.setItemText(6, QtGui.QApplication.translate("MainWindow", "Trollbloods", None, QtGui.QApplication.UnicodeUTF8))
        self.c_faction.setItemText(7, QtGui.QApplication.translate("MainWindow", "Skorne", None, QtGui.QApplication.UnicodeUTF8))
        self.c_faction.setItemText(8, QtGui.QApplication.translate("MainWindow", "Circle", None, QtGui.QApplication.UnicodeUTF8))
        self.c_faction.setItemText(9, QtGui.QApplication.translate("MainWindow", "Legion", None, QtGui.QApplication.UnicodeUTF8))
        self.c_faction.setItemText(10, QtGui.QApplication.translate("MainWindow", "Minions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Faction", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Team", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Country", None, QtGui.QApplication.UnicodeUTF8))
        self.b_addPlayer.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.t_players.setSortingEnabled(False)
        self.t_players.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.t_players.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.t_players.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Faction", None, QtGui.QApplication.UnicodeUTF8))
        self.t_players.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Team", None, QtGui.QApplication.UnicodeUTF8))
        self.t_players.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Country", None, QtGui.QApplication.UnicodeUTF8))
        self.t_players.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "TP", None, QtGui.QApplication.UnicodeUTF8))
        self.t_players.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "SoS", None, QtGui.QApplication.UnicodeUTF8))
        self.t_players.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("MainWindow", "CP", None, QtGui.QApplication.UnicodeUTF8))
        self.t_players.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("MainWindow", "KP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Edit Player", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Country", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Team", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Faction", None, QtGui.QApplication.UnicodeUTF8))
        self.c_faction_2.setItemText(0, QtGui.QApplication.translate("MainWindow", "Cygnar", None, QtGui.QApplication.UnicodeUTF8))
        self.c_faction_2.setItemText(1, QtGui.QApplication.translate("MainWindow", "Cryx", None, QtGui.QApplication.UnicodeUTF8))
        self.c_faction_2.setItemText(2, QtGui.QApplication.translate("MainWindow", "Khador", None, QtGui.QApplication.UnicodeUTF8))
        self.c_faction_2.setItemText(3, QtGui.QApplication.translate("MainWindow", "Menoth", None, QtGui.QApplication.UnicodeUTF8))
        self.c_faction_2.setItemText(4, QtGui.QApplication.translate("MainWindow", "Retribution", None, QtGui.QApplication.UnicodeUTF8))
        self.c_faction_2.setItemText(5, QtGui.QApplication.translate("MainWindow", "Mercs", None, QtGui.QApplication.UnicodeUTF8))
        self.c_faction_2.setItemText(6, QtGui.QApplication.translate("MainWindow", "Trollbloods", None, QtGui.QApplication.UnicodeUTF8))
        self.c_faction_2.setItemText(7, QtGui.QApplication.translate("MainWindow", "Skorne", None, QtGui.QApplication.UnicodeUTF8))
        self.c_faction_2.setItemText(8, QtGui.QApplication.translate("MainWindow", "Circle", None, QtGui.QApplication.UnicodeUTF8))
        self.c_faction_2.setItemText(9, QtGui.QApplication.translate("MainWindow", "Legion", None, QtGui.QApplication.UnicodeUTF8))
        self.c_faction_2.setItemText(10, QtGui.QApplication.translate("MainWindow", "Minions", None, QtGui.QApplication.UnicodeUTF8))
        self.b_editPlayer.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_players), QtGui.QApplication.translate("MainWindow", "Players", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Show pairings for round:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_startNextRound.setText(QtGui.QApplication.translate("MainWindow", "Start next round", None, QtGui.QApplication.UnicodeUTF8))
        self.t_pairings.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Table #", None, QtGui.QApplication.UnicodeUTF8))
        self.t_pairings.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Player A", None, QtGui.QApplication.UnicodeUTF8))
        self.t_pairings.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Player B", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_pairings), QtGui.QApplication.translate("MainWindow", "Pairings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Table number:", None, QtGui.QApplication.UnicodeUTF8))
        self.e_tblnum.setInputMask(QtGui.QApplication.translate("MainWindow", "009; ", None, QtGui.QApplication.UnicodeUTF8))
        self.e_tblnum.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "___", None, QtGui.QApplication.UnicodeUTF8))
        self.e_pAcp.setInputMask(QtGui.QApplication.translate("MainWindow", "9; ", None, QtGui.QApplication.UnicodeUTF8))
        self.e_pAcp.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "_", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "CP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Destroyed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Player A", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "TP", None, QtGui.QApplication.UnicodeUTF8))
        self.e_pAkp.setInputMask(QtGui.QApplication.translate("MainWindow", "009; ", None, QtGui.QApplication.UnicodeUTF8))
        self.e_pAkp.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "___", None, QtGui.QApplication.UnicodeUTF8))
        self.e_pAtp.setInputMask(QtGui.QApplication.translate("MainWindow", "9; ", None, QtGui.QApplication.UnicodeUTF8))
        self.e_pAtp.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "_", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Faction", None, QtGui.QApplication.UnicodeUTF8))
        self.c_pAfaction.setItemText(0, QtGui.QApplication.translate("MainWindow", "Cygnar", None, QtGui.QApplication.UnicodeUTF8))
        self.c_pAfaction.setItemText(1, QtGui.QApplication.translate("MainWindow", "Cryx", None, QtGui.QApplication.UnicodeUTF8))
        self.c_pAfaction.setItemText(2, QtGui.QApplication.translate("MainWindow", "Khador", None, QtGui.QApplication.UnicodeUTF8))
        self.c_pAfaction.setItemText(3, QtGui.QApplication.translate("MainWindow", "Menoth", None, QtGui.QApplication.UnicodeUTF8))
        self.c_pAfaction.setItemText(4, QtGui.QApplication.translate("MainWindow", "Retribution", None, QtGui.QApplication.UnicodeUTF8))
        self.c_pAfaction.setItemText(5, QtGui.QApplication.translate("MainWindow", "Mercs", None, QtGui.QApplication.UnicodeUTF8))
        self.c_pAfaction.setItemText(6, QtGui.QApplication.translate("MainWindow", "Trollbloods", None, QtGui.QApplication.UnicodeUTF8))
        self.c_pAfaction.setItemText(7, QtGui.QApplication.translate("MainWindow", "Skorne", None, QtGui.QApplication.UnicodeUTF8))
        self.c_pAfaction.setItemText(8, QtGui.QApplication.translate("MainWindow", "Circle", None, QtGui.QApplication.UnicodeUTF8))
        self.c_pAfaction.setItemText(9, QtGui.QApplication.translate("MainWindow", "Legion", None, QtGui.QApplication.UnicodeUTF8))
        self.c_pAfaction.setItemText(10, QtGui.QApplication.translate("MainWindow", "Minions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "TP", None, QtGui.QApplication.UnicodeUTF8))
        self.e_pBcp.setInputMask(QtGui.QApplication.translate("MainWindow", "9; ", None, QtGui.QApplication.UnicodeUTF8))
        self.e_pBcp.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "_", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "CP", None, QtGui.QApplication.UnicodeUTF8))
        self.e_pBtp.setInputMask(QtGui.QApplication.translate("MainWindow", "9; ", None, QtGui.QApplication.UnicodeUTF8))
        self.e_pBtp.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "_", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.e_pBkp.setInputMask(QtGui.QApplication.translate("MainWindow", "009; ", None, QtGui.QApplication.UnicodeUTF8))
        self.e_pBkp.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "___", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Player B", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Destroyed", None, QtGui.QApplication.UnicodeUTF8))
        self.c_pBfaction.setItemText(0, QtGui.QApplication.translate("MainWindow", "Cygnar", None, QtGui.QApplication.UnicodeUTF8))
        self.c_pBfaction.setItemText(1, QtGui.QApplication.translate("MainWindow", "Cryx", None, QtGui.QApplication.UnicodeUTF8))
        self.c_pBfaction.setItemText(2, QtGui.QApplication.translate("MainWindow", "Khador", None, QtGui.QApplication.UnicodeUTF8))
        self.c_pBfaction.setItemText(3, QtGui.QApplication.translate("MainWindow", "Menoth", None, QtGui.QApplication.UnicodeUTF8))
        self.c_pBfaction.setItemText(4, QtGui.QApplication.translate("MainWindow", "Retribution", None, QtGui.QApplication.UnicodeUTF8))
        self.c_pBfaction.setItemText(5, QtGui.QApplication.translate("MainWindow", "Mercs", None, QtGui.QApplication.UnicodeUTF8))
        self.c_pBfaction.setItemText(6, QtGui.QApplication.translate("MainWindow", "Trollbloods", None, QtGui.QApplication.UnicodeUTF8))
        self.c_pBfaction.setItemText(7, QtGui.QApplication.translate("MainWindow", "Skorne", None, QtGui.QApplication.UnicodeUTF8))
        self.c_pBfaction.setItemText(8, QtGui.QApplication.translate("MainWindow", "Circle", None, QtGui.QApplication.UnicodeUTF8))
        self.c_pBfaction.setItemText(9, QtGui.QApplication.translate("MainWindow", "Legion", None, QtGui.QApplication.UnicodeUTF8))
        self.c_pBfaction.setItemText(10, QtGui.QApplication.translate("MainWindow", "Minions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "Faction", None, QtGui.QApplication.UnicodeUTF8))
        self.b_saveResult.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_results), QtGui.QApplication.translate("MainWindow", "Enter Results", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_players_from_CSV.setText(QtGui.QApplication.translate("MainWindow", "Load players from CSV", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_tournament_state.setText(QtGui.QApplication.translate("MainWindow", "Save tournament state", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_tournament_state.setText(QtGui.QApplication.translate("MainWindow", "Load tournament state", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Players.setText(QtGui.QApplication.translate("MainWindow", "Load Players", None, QtGui.QApplication.UnicodeUTF8))

